source "https://rubygems.org"

gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'sqlite3'
gem 'pry'
gem 'require_all'
gem 'rack'
gem 'shotgun'
gem 'sinatra'
gem 'rest-client'

# Added at 2018-06-07 15:32:55 -0400 by graham.troyer-joy:
# this makes cookies work
gem "sinatra-contrib", "~> 2.0"

# Added at 2018-06-07 15:43:39 -0400 by graham.troyer-joy:
# this makes flash work
gem "sinatra-flash", "~> 0.3.0"
