require_relative './config/environment'
require 'sinatra/activerecord/rake'

desc "Start our app console"
task :console do
  Pry.start
end

desc "Tells the world hello!"
task :helloworld do
  puts "HELLO WORLD!!!!!"
end
